/* tslint:disable */
/* eslint-disable */
/**
 * Squad API
 * Squad is an AI product management platform that analyses customer feedback, surfaces insights, and builds prioritised roadmaps. Use this API to manage goals, opportunities, solutions, feedback, and more.
 *
 * The version of the OpenAPI document: 4.15.0
 * Contact: hello@meetsquad.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WhoAmIResponseDataOrganisation } from './WhoAmIResponseDataOrganisation';
import {
    WhoAmIResponseDataOrganisationFromJSON,
    WhoAmIResponseDataOrganisationFromJSONTyped,
    WhoAmIResponseDataOrganisationToJSON,
    WhoAmIResponseDataOrganisationToJSONTyped,
} from './WhoAmIResponseDataOrganisation';
import type { WhoAmIResponseDataWorkspace } from './WhoAmIResponseDataWorkspace';
import {
    WhoAmIResponseDataWorkspaceFromJSON,
    WhoAmIResponseDataWorkspaceFromJSONTyped,
    WhoAmIResponseDataWorkspaceToJSON,
    WhoAmIResponseDataWorkspaceToJSONTyped,
} from './WhoAmIResponseDataWorkspace';

/**
 * 
 * @export
 * @interface WhoAmIResponseData
 */
export interface WhoAmIResponseData {
    /**
     * 
     * @type {WhoAmIResponseDataOrganisation}
     * @memberof WhoAmIResponseData
     */
    organisation: WhoAmIResponseDataOrganisation;
    /**
     * 
     * @type {WhoAmIResponseDataWorkspace}
     * @memberof WhoAmIResponseData
     */
    workspace: WhoAmIResponseDataWorkspace;
}

/**
 * Check if a given object implements the WhoAmIResponseData interface.
 */
export function instanceOfWhoAmIResponseData(value: object): value is WhoAmIResponseData {
    if (!('organisation' in value) || value['organisation'] === undefined) return false;
    if (!('workspace' in value) || value['workspace'] === undefined) return false;
    return true;
}

export function WhoAmIResponseDataFromJSON(json: any): WhoAmIResponseData {
    return WhoAmIResponseDataFromJSONTyped(json, false);
}

export function WhoAmIResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WhoAmIResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'organisation': WhoAmIResponseDataOrganisationFromJSON(json['organisation']),
        'workspace': WhoAmIResponseDataWorkspaceFromJSON(json['workspace']),
    };
}

export function WhoAmIResponseDataToJSON(json: any): WhoAmIResponseData {
    return WhoAmIResponseDataToJSONTyped(json, false);
}

export function WhoAmIResponseDataToJSONTyped(value?: WhoAmIResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organisation': WhoAmIResponseDataOrganisationToJSON(value['organisation']),
        'workspace': WhoAmIResponseDataWorkspaceToJSON(value['workspace']),
    };
}

